apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
  namespace: jenkins
spec:
  imagePullSecrets:
  - name: image-secret
  containers:
  - image: jenkins/inbound-agent:4.3-4-jdk11
    imagePullPolicy: IfNotPresent
    name: jnlp
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    volumeMounts:
    - mountPath: /home/jenkins/agent
      name: workspace-cache
    workingDir: /home/jenkins/agent
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
  - args:
    - "9999999"
    command:
    - sleep
    image: docker:latest
    imagePullPolicy: IfNotPresent
    name: docker
    env:
    - name: DOCKER_HOST
      value: tcp://dind-service:2375
    - name: DOCKER_TLS_VERIFY
      value: ""
    volumeMounts:
      - mountPath: /home/jenkins/agent
        name: workspace-cache
    workingDir: /home/jenkins/agent
  volumes:
  - name: workspace-cache
    emptyDir: {}